apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos
subjects:
- kind: ServiceAccount
  name: chaos
  namespace: default
roleRef:
  kind: ClusterRole
  name: chaos
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: chaos
spec:
  serviceAccountName: chaos
  containers:
  - name: chaos
    image: kunchalavikram/chaos-monkey:1.0
    imagePullPolicy: Always
    env:
    - name: INTERVAL
      value: "10"
    - name: NAMESPACE
      value: "dev"
    - name: MY_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
