apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectedcity-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: connectedcity
  template:
    metadata:
      labels:
        app: connectedcity
    spec:
      containers:
      - name: connectedcity
        image: kunchalavikram/connectedcity:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: connectedcity-service
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: connectedcity

